services:
  db:
    image: postgres:13-alpine
    volumes:
      - db_python:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=carros
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
volumes:
  db_python: